CREATE TABLE IF NOT EXISTS stations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    station_code VARCHAR(120) NOT NULL,
    province VARCHAR(120) NULL,
    municipality VARCHAR(120) NULL,
    locality VARCHAR(120) NULL,
    postal_code VARCHAR(20) NULL,
    address VARCHAR(255) NULL,
    margin VARCHAR(20) NULL,
    longitude DECIMAL(12,8) NULL,
    latitude DECIMAL(12,8) NULL,
    brand VARCHAR(150) NULL,
    sale_type VARCHAR(20) NULL,
    provider VARCHAR(20) NULL,
    hours VARCHAR(255) NULL,
    service_type VARCHAR(20) NULL,
    municipality_code VARCHAR(20) NULL,
    province_code VARCHAR(20) NULL,
    autonomous_community_code VARCHAR(20) NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY stations_station_code_unique (station_code),
    KEY stations_province_index (province),
    KEY stations_municipality_index (municipality),
    KEY stations_brand_index (brand)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    station_id BIGINT UNSIGNED NOT NULL,
    collected_at DATETIME NOT NULL,
    gas95_e5 DECIMAL(8,3) NULL,
    gas95_e10 DECIMAL(8,3) NULL,
    gas95_e25 DECIMAL(8,3) NULL,
    gas95_e5_premium DECIMAL(8,3) NULL,
    gas95_e85 DECIMAL(8,3) NULL,
    gas98_e5 DECIMAL(8,3) NULL,
    gas98_e10 DECIMAL(8,3) NULL,
    renewable_gasoline DECIMAL(8,3) NULL,
    diesel_a DECIMAL(8,3) NULL,
    diesel_b DECIMAL(8,3) NULL,
    diesel_premium DECIMAL(8,3) NULL,
    renewable_diesel DECIMAL(8,3) NULL,
    bioethanol DECIMAL(8,3) NULL,
    pct_bio DECIMAL(8,3) NULL,
    biodiesel DECIMAL(8,3) NULL,
    pct_ester DECIMAL(8,3) NULL,
    glp DECIMAL(8,3) NULL,
    gnc DECIMAL(8,3) NULL,
    gnl DECIMAL(8,3) NULL,
    biogas_cng DECIMAL(8,3) NULL,
    biogas_lng DECIMAL(8,3) NULL,
    hydrogen DECIMAL(8,3) NULL,
    adblue DECIMAL(8,3) NULL,
    ammonia DECIMAL(8,3) NULL,
    methanol DECIMAL(8,3) NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY prices_station_collected_unique (station_id, collected_at),
    KEY prices_collected_at_index (collected_at),
    KEY prices_station_id_index (station_id),
    CONSTRAINT prices_station_id_foreign FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
