<?php

return [
    'source_url' => env('PRICE_IMPORT_SOURCE', 'https://geoportalgasolineras.es/resources/files/preciosEESS_es.xls'),
    'rest_source_url' => env('PRICE_IMPORT_REST_SOURCE', 'https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/'),
    'import_token' => env('PRICE_IMPORT_TOKEN', ''),
    'import_strategy' => env('PRICE_IMPORT_STRATEGY', 'auto'),
    'default_fuel' => 'diesel_a',
    'featured_fuels' => [
        'diesel_a' => ['label' => 'Gasóleo A', 'short' => 'Diésel A'],
        'gas95_e10' => ['label' => 'Gasolina 95 E10', 'short' => 'Gasolina 95'],
        'gas98_e5' => ['label' => 'Gasolina 98 E5', 'short' => 'Gasolina 98'],
        'diesel_premium' => ['label' => 'Gasóleo Premium', 'short' => 'Diésel Premium'],
        'glp' => ['label' => 'GLP', 'short' => 'GLP'],
        'gnc' => ['label' => 'Gas natural comprimido', 'short' => 'GNC'],
    ],
    'fuels' => [
        'gas95_e5' => ['label' => 'Gasolina 95 E5', 'group' => 'gasolinas'],
        'gas95_e10' => ['label' => 'Gasolina 95 E10', 'group' => 'gasolinas'],
        'gas95_e25' => ['label' => 'Gasolina 95 E25', 'group' => 'gasolinas'],
        'gas95_e5_premium' => ['label' => 'Gasolina 95 E5 Premium', 'group' => 'gasolinas'],
        'gas95_e85' => ['label' => 'Gasolina 95 E85', 'group' => 'gasolinas'],
        'gas98_e5' => ['label' => 'Gasolina 98 E5', 'group' => 'gasolinas'],
        'gas98_e10' => ['label' => 'Gasolina 98 E10', 'group' => 'gasolinas'],
        'renewable_gasoline' => ['label' => 'Gasolina renovable', 'group' => 'gasolinas'],
        'diesel_a' => ['label' => 'Gasóleo A', 'group' => 'gasoleos'],
        'diesel_b' => ['label' => 'Gasóleo B', 'group' => 'gasoleos'],
        'diesel_premium' => ['label' => 'Gasóleo Premium', 'group' => 'gasoleos'],
        'renewable_diesel' => ['label' => 'Diésel renovable', 'group' => 'gasoleos'],
        'biodiesel' => ['label' => 'Biodiésel', 'group' => 'alternativos'],
        'bioethanol' => ['label' => 'Bioetanol', 'group' => 'alternativos'],
        'pct_bio' => ['label' => '% Bioetanol', 'group' => 'alternativos'],
        'pct_ester' => ['label' => '% Éster metílico', 'group' => 'alternativos'],
        'glp' => ['label' => 'GLP', 'group' => 'gases'],
        'gnc' => ['label' => 'Gas natural comprimido', 'group' => 'gases'],
        'gnl' => ['label' => 'Gas natural licuado', 'group' => 'gases'],
        'biogas_cng' => ['label' => 'Biogás comprimido', 'group' => 'gases'],
        'biogas_lng' => ['label' => 'Biogás licuado', 'group' => 'gases'],
        'hydrogen' => ['label' => 'Hidrógeno', 'group' => 'alternativos'],
        'adblue' => ['label' => 'AdBlue', 'group' => 'servicios'],
        'ammonia' => ['label' => 'Amoniaco', 'group' => 'alternativos'],
        'methanol' => ['label' => 'Metanol', 'group' => 'alternativos'],
    ],
    'legal_notice' => 'Estos datos pueden variar a medida que las gasolineras notifiquen sus precios al sistema durante el día.',
    'history_days' => [7, 14, 30, 90],
    'cheapest_page_size' => 20,
    'search_page_size' => 12,
];
